fix:issue-60/tweets in threads
holdex/holdex-venture-studio pull request #317
Opened 2023-05-24 18:44 UTC by surajsharma

- successfully migrated [twitter-widget](https://github.com/holdex/twitter-widget) component into the repo
- redesigned the tweet widget as per new design
- tweets are now rendering within threads
- ~~using a CORS proxy for fetching tweets as a temporary measure~~
- migrated css too tailwind where possible

fixes #60

2023-06-06 11:13 UTC, georgeciubotaru commented
@surajsharma Please see this tab, and try to check for unresolved comments: https://github.com/holdex/holdex-venture-studio/pull/317/files

2023-06-06 15:20 UTC, surajsharma commented
@georgeciubotaru done

2023-06-07 05:38 UTC, georgeciubotaru commented on src/lib/components/BodyRenderer/Blocks/Tweet/components/twitter-layout/LinkPreview/style.sass
> +        transition: background-color 0.3s ease-in-out, border-color 0.3s ease-in-out
@surajsharma try to put the `@apply` as the last property, to avoid the wrong indentation

2023-06-07 05:41 UTC, georgeciubotaru commented on src/lib/components/BodyRenderer/Blocks/Tweet/components/twitter-layout/headings/permalink.svelte
> +        @apply mr-2
indentation is wrong

2023-06-07 05:43 UTC, georgeciubotaru commented
@surajsharma Last comments

1. Still we have dev dependencies that we don't need
2. lib folder is present (we don't need it)
3. importing `theme.scss` in the Twitter components (we don't need it as it will inherit from the main layout)
4. See my comments above

2023-06-07 06:46 UTC, surajsharma commented
@georgeciubotaru 

1. removed unused dev deps, including all `@types`
2. deleted the said folder, sorry didn't feel confident deleting earlier
3. can you show me where this is in the code? i searched but found nothing, have deleted all of these
4. fixed

2023-06-07 07:16 UTC, surajsharma commented on src/lib/components/BodyRenderer/Blocks/Tweet/components/twitter-layout/LinkPreview/style.sass
> +        transition: background-color 0.3s ease-in-out, border-color 0.3s ease-in-out
@georgeciubotaru although i have put it as a last property, i think we can do away with it here altogether

2023-06-07 08:47 UTC, markholdex commented
@surajsharma @georgeciubotaru what are we missing to complete this task?

2023-06-07 09:06 UTC, surajsharma commented
@markholdex all done at my end, waiting on @georgeciubotaru for the final word

2023-06-07 13:52 UTC, georgeciubotaru commented on src/lib/components/BodyRenderer/Blocks/Tweet/components/twitter-layout/LinkPreview/style.sass
> +        relative w-full block text-[15px] leading-5 whitespace-normal p-3 @apply
@surajsharma not like that
```
.class {
	// CSS declarations
	text-align: center
	@apply text-center
}
```
In that case the `CSS` declaration won't be indented  like that
```
.class {
	@apply text-center
		// CSS declarations
		text-align: center
}
```

2023-06-07 13:53 UTC, georgeciubotaru commented on package.json
> -		"@types/lodash-es": "^4.17.7",
@surajsharma add types back

2023-06-07 13:53 UTC, georgeciubotaru commented on package.json
> +		"twitter-text": "^3.1.0",
remove these ones

2023-06-07 13:54 UTC, georgeciubotaru commented on src/lib/components/BodyRenderer/Blocks/Tweet/components/twitter-layout/Tweet/TweetAction.svelte
> +    @import "../../../../../../../styles/theme"
check for this import in all files.

You don't need it

2023-06-07 13:55 UTC, georgeciubotaru requested changes
@surajsharma See my changes, iterate in all files and to the updates

2023-06-07 15:13 UTC, surajsharma commented on src/lib/components/BodyRenderer/Blocks/Tweet/components/twitter-layout/LinkPreview/style.sass
> +        relative w-full block text-[15px] leading-5 whitespace-normal p-3 @apply
@georgeciubotaru fixed, pls see

2023-06-07 16:16 UTC, georgeciubotaru commented on package.json
> -		"@types/rimraf": "^4.0.5",
these put back

2023-06-07 16:17 UTC, georgeciubotaru commented on package.json
> -		"tslib": "^2.4.1",
@surajsharma see the removed deps and keep only the ones we are using

2023-06-07 16:17 UTC, georgeciubotaru commented on package.json
> -		"dotenv": "^16.0.3",
we need this

2023-06-07 16:19 UTC, georgeciubotaru commented
@surajsharma the last ones and is good to go.

Good job!

Hope we will minimize the back and forth in the future PR.

2023-06-07 17:10 UTC, surajsharma commented on package.json
> -		"tslib": "^2.4.1",
@georgeciubotaru i search for `tslib` but no use found, closing...

2023-06-07 17:12 UTC, surajsharma commented
@georgeciubotaru yes i look forward to smaller PRs :)

2023-06-08 05:40 UTC, georgeciubotaru commented
@surajsharma On It

2023-06-08 06:40 UTC, merged