Fix rendering table component
holdex/holdex-venture-studio pull request #396
Opened 2023-06-16 07:21 UTC by accompany1205

Fix #225

2023-06-16 07:22 UTC, accompany1205 commented
@zolotokrylin , @georgeciubotaru Could you review this PR please?

2023-06-16 08:34 UTC, accompany1205 commented
@zolotokrylin , @georgeciubotaru I'm waiting for your feedback.

2023-06-16 10:52 UTC, zolotokrylin commented
@accompany1205 please resolve merge conflicts. Thanks!

2023-06-16 13:11 UTC, accompany1205 commented
@zolotokrylin Resolved conflicts.

2023-06-16 13:56 UTC, accompany1205 commented
@zolotokrylin I know you're in the late evening.
However, if it's possible for you, could you review this PR before today ends?
The weekend is upcoming, so I would like to wrap out my work today.

2023-06-16 14:06 UTC, georgeciubotaru commented on src/lib/components/BodyRenderer/Blocks/tableCell.pug
> ++if("typeof cell === 'object'")
@accompany1205 You get the point here, but this implementation is not DRY. you are repeating the existing code from `BodyRenderer/template.pug`. How about fixing that?

2023-06-16 14:10 UTC, georgeciubotaru commented on src/lib/components/BodyParser/blocks.ts
>  const parseTable = (block: TableBlock) => {
@accompany1205 how about using the existing function to parse nested elements?

Like `block.data.content.forEach(row => tableContent.push(parseBlocks(row))}`?

2023-06-16 15:20 UTC, georgeciubotaru commented
@markcurchin Please help with the UI review, if all good and my last comment is fixed, feel free to merge.

Note: Add yourself as Co-Author to   resolve merging issues.

2023-06-16 15:33 UTC, accompany1205 commented
@markcurchin , @georgeciubotaru When I flag `previewMock` to true, I can see this table in http://localhost:3000/c/learn/holdex-hr-guidelines
![image](https://github.com/holdex/holdex-venture-studio/assets/96562726/479ecfd2-efa8-4df3-a1c4-bf4b65b43ed7)
The number of columns are not identical since of poor response.

2023-06-16 19:38 UTC, markholdex commented
@accompany1205 seems like something is wrong with the table component after the previous changes? Because I can't create articles with table anymore either.

2023-06-16 19:55 UTC, accompany1205 commented
@markholdex I think that there are no issues in rendering table component with given data and its structure.
Could you let me know what is blocking you to create articles?

2023-06-19 07:08 UTC, markholdex commented
@accompany1205 for some reason the table content doesn't load. I've restart the build on your branch. here, have a look: https://holdex-venture-studio-git-fork-accomp-48163e-holdex-accelerator.vercel.app/c/announcements/article-components

and compare it to stage: https://stage.holdex.io/c/announcements/article-components

2023-06-19 07:14 UTC, accompany1205 commented
@markholdex there is no difference between them.

2023-06-19 07:15 UTC, accompany1205 commented
@markholdex , @georgeciubotaru how can I reproduce the issue on my local repo?

2023-06-19 07:45 UTC, georgeciubotaru commented
@accompany1205 Just replace the domain with the `localhost:3000`, the rest remains the same.

e.g.
https://holdex-venture-studio-git-fork-accomp-48163e-holdex-accelerator.vercel.app/c/announcements/article-components ~~ http://localhost:3000/c/announcements/article-components

2023-06-19 13:09 UTC, accompany1205 commented
@markholdex , @georgeciubotaru This is because we haven't got expected data structure of table content from response.
Each table cell should have the data structure or an independent block.
- Like this 
![image](https://github.com/holdex/holdex-venture-studio/assets/96562726/7004efd0-1e7a-403d-9d40-e7e9484281a5)
- but in this [page](http://localhost:3000/c/announcements/article-components) the content of a table cell is just a string.
![image](https://github.com/holdex/holdex-venture-studio/assets/96562726/4d4f2e06-cabf-4026-91f6-2ad96d8e7c3a)

2023-06-19 14:06 UTC, markholdex commented
@accompany1205 I believe these changes were introduced in your PR https://github.com/holdex/holdex-venture-studio/pull/382 where you have worked on the table parsing. Can you please continue and fix the current issue?

2023-06-19 14:20 UTC, accompany1205 commented
@markholdex Yes, I made the changes in the PR #382 to address the issue #309.
In the issue, we expected the response that table cells have got individual blocks.
Please see issue description and comments of the issue #309 
https://api.npoint.io/c8d0bf6bfd4cdb54328d
https://github.com/holdex/holdex-venture-studio/issues/309#issuecomment-1561220369

2023-06-19 14:23 UTC, accompany1205 commented
@markholdex I think the best solution is to get a response that we expect from backend server.

2023-06-19 14:37 UTC, accompany1205 commented
@georgeciubotaru Is there anything that I misunderstand about the issue #309 and this(#225)?
I think we're trying to show individual blocks like nested list, paragraph, list, header, etc in table cells.
To do that, arrays of string is not allowed
`['Event name', 'Date', 'Time', 'Location', 'Desc', 'Entry']`
Am I right?
Could you let me know what I can do to wrap out this issue?

2023-06-20 01:55 UTC, accompany1205 commented
@markholdex Could you review again? I updated

2023-06-20 08:52 UTC, accompany1205 commented
@markholdex I'm waiting for your feedback.

2023-06-20 14:52 UTC, accompany1205 commented
@markholdex did you have a chance to review updates on this PR?

2023-06-20 14:52 UTC, zolotokrylin commented
@accompany1205 far are you from resolving this PR? 
Relevant to: https://github.com/holdex/holdex-venture-studio/issues/403#issuecomment-1598766249

2023-06-20 14:55 UTC, accompany1205 commented
@zolotokrylin I think all is done. I'm waiting for @markholdex 's feedback

2023-06-20 15:36 UTC, markholdex commented
@power-f-GOD can you please code review this PR? Thanks 🙏

2023-06-20 19:32 UTC, accompany1205 commented
@markholdex George already did code review except last [commit](https://github.com/holdex/holdex-venture-studio/pull/396/commits/9ebb2fc25538e078749faa1aceac3c3e2946c5d9).
So you need to review only last commit.

2023-06-21 05:45 UTC, power-f-GOD reviewed
PR's code-good-to-go, just a few trivial adjustments that may be done.✔️

Cc: @markholdex

2023-06-21 05:45 UTC, power-f-GOD commented on src/lib/components/BodyParser/blocks.ts
> +		content: Array<Array<any>>;
Hi, @accompany1205 , kindly, is there a reason for changing from `string` to `any`? Can you use an actual type instead of `any`?

2023-06-21 05:45 UTC, power-f-GOD commented on src/lib/components/BodyParser/blocks.ts
> +	};
These don't seem to be well-indented.🤔 Or is it my eyes?😅

2023-06-21 05:45 UTC, power-f-GOD commented on src/lib/components/BodyParser/blocks.ts
> +	const tableContent: any[] = [];
If it's possible to give any other type than `any`, please do. `any` is a bug ally, hence it makes it harder for us to catch them. 🤲🏼

2023-06-21 05:45 UTC, power-f-GOD commented on src/lib/components/BodyRenderer/Blocks/table.svelte
> +	export let cells: any[];
Indentation.

2023-06-21 05:45 UTC, power-f-GOD commented on src/lib/components/BodyRenderer/item.svelte
> +	import Table from './Blocks/table.svelte';
Indentation.

2023-06-21 06:17 UTC, georgeciubotaru commented
Log: I'm reviewing the PR

2023-06-21 07:19 UTC, georgeciubotaru requested changes
see my comments

2023-06-21 07:19 UTC, georgeciubotaru commented on src/lib/components/BodyRenderer/Blocks/tableCell.svelte
> +<script lang="ts">
@accompany1205 How about getting rid of this file and use directly the `Item` component

2023-06-21 07:19 UTC, georgeciubotaru commented on src/lib/components/BodyRenderer/item.pug
> +      Image(item="{item}" index="{index}")
@accompany1205 You are missing the index value here

2023-06-21 07:30 UTC, georgeciubotaru commented
@accompany1205 I also updated the API parser, so the `Body` will also require to be updated.

let me know which thread are you using for testing, so I can update them with the new format

2023-06-21 12:44 UTC, accompany1205 commented on src/lib/components/BodyParser/blocks.ts
> +		content: Array<Array<any>>;
@power-f-GOD Because each table cell might have an individual block like paragraph, list, code etc in it.
Please the issue #309

2023-06-21 13:17 UTC, accompany1205 commented on src/routes/(pages)/c/[slug]/[messageSlug]/template.pug
> -    +else: {message._author.name}
with this code `+else: {message._author.name}`, I meet a crash
![image](https://github.com/holdex/holdex-venture-studio/assets/96562726/b3ff3165-fddd-4882-83b2-5b9071ab21c7)

2023-06-21 13:23 UTC, georgeciubotaru commented on src/routes/(pages)/c/[slug]/[messageSlug]/template.pug
> -    +else: {message._author.name}
It's resolved

2023-06-21 13:41 UTC, georgeciubotaru commented on src/lib/components/BodyParser/blocks.ts
> +  block.data.content.forEach((row) => tableContent.push(parseBlocks(row)));
here row type is`Array<Array<Array<HeadingBlock | ParagraphBlock | ListBlock | NestedListBlock | ImageBlock | CodeBlock>>>;

2023-06-21 14:41 UTC, georgeciubotaru commented on src/lib/components/BodyParser/blocks.ts
> +  block.data.content.forEach((row) => tableContent.push(parseBlocks(row)));
@accompany1205 The `parseBlocks()` will receive an Array of Arrays as input and fail to parse elements.

2023-06-21 15:15 UTC, accompany1205 commented on src/lib/components/BodyParser/blocks.ts
> +  block.data.content.forEach((row) => tableContent.push(parseBlocks(row)));
@georgeciubotaru I can't see that it fails. Where can you see that?
Could you show me a screen shot?

2023-06-21 15:21 UTC, accompany1205 commented
@georgeciubotaru Are there any comments that I missed?
I think all comments have been resolved

2023-06-21 15:53 UTC, accompany1205 commented
@georgeciubotaru I'm waiting for your feedback.

2023-06-21 16:07 UTC, georgeciubotaru approved these changes

2023-06-21 16:07 UTC, georgeciubotaru commented
@accompany1205 You can see my commits to understanding the issue I've reported in comments.

2023-06-21 16:09 UTC, merged