feat: user subscription component added
holdex/holdex-venture-studio pull request #453
Opened 2023-07-13 17:40 UTC by MuhammadArslanKhan96

added subscription component, didn't integrate graphql and other backend at the moment.

Github Issue: https://github.com/holdex/holdex-venture-studio/issues/372

2023-07-13 20:15 UTC, markholdex commented
@predrag-us please have a look. Thx 🙏

2023-07-14 11:47 UTC, predrag-us commented
@MuhammadArslanKhan96 

Can you send me a direct URL where I can see this component? Thanks!

2023-07-14 12:42 UTC, markholdex commented
@predrag-us I restarted the build. Try in a few minutes

2023-07-14 12:52 UTC, predrag-us commented
@MuhammadArslanKhan96 

- SubscribeCTA component isn't implemented according to the design
- Buttons aren't implemented according to the design
- Modal component isn't implemented according to the design
- Responsive isn't tackled 
- I shouldn't be able to subscribe without entering an email
- Images are blurred

Please take more time and notice the details. 

Thank you!

2023-07-14 14:26 UTC, MuhammadArslanKhan96 commented
@predrag-us let me check

2023-07-15 14:40 UTC, MuhammadArslanKhan96 commented
@predrag-us I've added the changes same as you explained in the comment

Kindly check it out

2023-07-17 08:06 UTC, georgeciubotaru commented on src/lib/styles/variables.scss
> +  l7: toSpacedRgba(#dcdee5),
@MuhammadArslanKhan96 Why do you need to add additional colors?

2023-07-17 08:07 UTC, georgeciubotaru commented on src/lib/styles/variables.scss
> +  t5: toSpacedRgb(#10141f),
@MuhammadArslanKhan96 Same here

2023-07-17 08:08 UTC, georgeciubotaru commented on src/routes/(pages)/c/+page.svelte
> +  import clickOutside from '$routes/(pages)/c/clickoutside';
@MuhammadArslanKhan96 this looks like a util function and should be placed in the corresponding folder.

2023-07-17 08:11 UTC, georgeciubotaru commented on static/avatar-2.png
we don't need these files, they are only for displaying the UI perspective. We should have here only 1 file with the fallback icon in case the user one will be missing.

2023-07-17 08:12 UTC, predrag-us commented
@MuhammadArslanKhan96 

I see no changes. Are you sure you pushed your work?

2023-07-17 08:19 UTC, MuhammadArslanKhan96 commented on src/lib/styles/variables.scss
> +  l7: toSpacedRgba(#dcdee5),
@georgeciubotaru because I want to get this color in rgba with opacity nothing much

2023-07-17 08:20 UTC, georgeciubotaru requested changes
see my changes.

This PR resolves half of the Problem, that's why it shouldn't be available for all users, or just available on a custom route until the feature will be fully covered

2023-07-17 08:20 UTC, georgeciubotaru commented on tailwind.config.cjs
> +    }
@MuhammadArslanKhan96 What is the purpose of these classes, and why we cannot use the `classes` provided by default by `Tailwind`?

2023-07-17 08:20 UTC, georgeciubotaru commented on tailwind.config.cjs
> +        50: '0.50',
@MuhammadArslanKhan96 same here

2023-07-17 08:20 UTC, georgeciubotaru commented on src/lib/styles/variables.scss
> +  shadow-modal: 0.32,
@MuhammadArslanKhan96 this object is only related to the Twitter component.

Regarding your fields they should be declared in the `tailwind` config file

2023-07-17 08:20 UTC, georgeciubotaru commented on src/routes/(pages)/c/clickoutside.ts
> +const clickOutside = (node: any) => {
@MuhammadArslanKhan96 why not send clickHandler as the second param?

2023-07-17 08:21 UTC, georgeciubotaru commented on src/lib/styles/variables.scss
> +  l7: toSpacedRgba(#dcdee5),
@MuhammadArslanKhan96 
for that, we have Tailwind classes. PLease check their documentation regarding that

2023-07-17 09:14 UTC, MuhammadArslanKhan96 reviewed
Kindly check now I've done my changes @georgeciubotaru

2023-07-17 13:35 UTC, georgeciubotaru commented on tailwind.config.cjs
> +      m1: '#10141f',
no need this

2023-07-17 13:45 UTC, MuhammadArslanKhan96 commented on tailwind.config.cjs
> +      m1: '#10141f',
Ok let me remove it

2023-07-17 13:47 UTC, MuhammadArslanKhan96 commented on tailwind.config.cjs
> +      m1: '#10141f',
![image](https://github.com/holdex/holdex-venture-studio/assets/98827339/837af598-9cca-462c-ae45-49c4096ee179)

Without that variable the code will be like this see line 147 & 158

2023-07-17 13:55 UTC, arslanpixpel commented on tailwind.config.cjs
> +      m1: '#10141f',
and also we can't manage for dark and light themes

2023-07-17 13:58 UTC, MuhammadArslanKhan96 commented on tailwind.config.cjs
> +      m1: '#10141f',
also its won't be manageable for light nd dark theme

2023-07-17 14:01 UTC, georgeciubotaru commented on tailwind.config.cjs
> +      m1: '#10141f',
@MuhammadArslanKhan96 We have this color declared, just check for the correct naming

2023-07-17 14:06 UTC, MuhammadArslanKhan96 commented on tailwind.config.cjs
> +      m1: '#10141f',
yes its there but the problem is, unsubscribe text black in both light and black theme, so if I use from the existing variables then requirements will not satisfied

2023-07-17 14:21 UTC, georgeciubotaru commented on tailwind.config.cjs
> +      m1: '#10141f',
`text-t1 dark:text-t4` of something like that

2023-07-17 14:26 UTC, MuhammadArslanKhan96 commented on tailwind.config.cjs
> +      m1: '#10141f',
Done I've changed like that Check it out! @georgeciubotaru

2023-07-18 12:14 UTC, georgeciubotaru commented
@predrag-us Please review the UI, I've approved the latest commit

2023-07-18 12:41 UTC, arslanpixpel commented
@predrag-us,  @georgeciubotaru suggested keep 1 image and remove rest

2023-07-18 12:47 UTC, MuhammadArslanKhan96 commented
@predrag-us , @georgeciubotaru  suggested keep just 1 image and remove rest

2023-07-18 12:50 UTC, georgeciubotaru commented
@MuhammadArslanKhan96 focus on the other issue, images are not an issue now, just double check their size and how they are looking then are 2 items

2023-07-18 16:24 UTC, MuhammadArslanKhan96 commented
Why some of tailwind default classses are not working like for width and max width

2023-07-19 06:25 UTC, georgeciubotaru commented
@MuhammadArslanKhan96 If the written class doesn't work may be for 2 reasons

- the class is not available
- the compiler cannot apply the change

For 1 reason check the class name one more time
For the second reason, try to trigger a change in the `tailwind.config` file

2023-07-24 13:54 UTC, MuhammadArslanKhan96 commented
Hey @georgeciubotaru , 
I'm having problem with height of the gradient line in subscription cta for that I've to define a class for height in tailwind config because the line is of 1px and tailwind is not providing any class for 1px and same with width of subscription CTA in mobile screen can I define maxWidth for subscription CTA and height for the line?

2023-07-25 05:41 UTC, georgeciubotaru commented
hey @MuhammadArslanKhan96 

For width and height
https://tailwindcss.com/docs/width

Regarding `max-width` if their classes cannot help just use directly e.g. `max-w-[630px]`

2023-07-25 07:41 UTC, MuhammadArslanKhan96 commented
Hey @predrag-us @georgeciubotaru , 
Can you guys check it now and tell me if there is  anything remaining?

2023-07-25 08:13 UTC, predrag-us commented
@georgeciubotaru 
Updated preview required.

2023-07-25 12:08 UTC, markholdex commented
@predrag-us please have a look. Thx

2023-07-25 16:17 UTC, MuhammadArslanKhan96 commented
@predrag-us I've compared with figma 2 to 3 times and all padding margin sizes formats weight everything is same,
could you please share detail what exactly is missing or mismatched with figma. thanks

2023-07-26 07:02 UTC, predrag-us commented
@MuhammadArslanKhan96 

I've recommended you an extension in this comment ⏤ https://github.com/holdex/holdex-venture-studio/pull/453#issuecomment-1635820955.

Please try comparing your implementation with the extension.

2023-07-26 09:37 UTC, MuhammadArslanKhan96 commented
I've checked and updated the design you were correct there were so much mistakes and thanks for telling about extension

That was very helpul @predrag-us

2023-07-26 09:52 UTC, predrag-us commented
@georgeciubotaru Can you please update the preview? Thank you!

2023-07-26 10:08 UTC, predrag-us commented
@MuhammadArslanKhan96 

This happens when I go to `/studio`. 

https://github.com/holdex/holdex-venture-studio/assets/18451941/99979c80-8cb4-4168-b82a-19936ca3e7f1

2023-07-26 10:11 UTC, MuhammadArslanKhan96 commented
Can you check it now @predrag-us ?

2023-07-26 10:26 UTC, predrag-us commented
@georgeciubotaru Another preview is needed. Thanks!

2023-07-26 15:25 UTC, MuhammadArslanKhan96 commented
Last question @predrag-us ,

I'm trying to apply class pl-1.5 because it's for 6px mentioned in tailwind docs but it's getting applied 
Many more classes are not applying that's why I'm having issues again and again

2023-07-27 06:06 UTC, georgeciubotaru commented
@MuhammadArslanKhan96 If you remember my solution.

Restart the `tailwind-config` file my changing something and then put it back, or restart the server.

2023-07-27 06:38 UTC, MuhammadArslanKhan96 commented
@predrag-us @georgeciubotaru 
I found the problem,
There was some config missing in preprocess file, I've added and all classes working smoothly

2023-07-27 07:54 UTC, MuhammadArslanKhan96 commented
@georgeciubotaru  please check the latest config

2023-07-27 10:11 UTC, MuhammadArslanKhan96 commented
@predrag-us I hope it will work now

2023-07-27 10:46 UTC, predrag-us commented
@georgeciubotaru Please release a new preview when you get a chance. Thank you!

2023-07-27 10:50 UTC, georgeciubotaru commented
@predrag-us Already done

2023-07-27 11:12 UTC, predrag-us commented
@MuhammadArslanKhan96 

I see no differences in the last preview. 

Can you please let me know what you updated?

2023-07-27 12:27 UTC, MuhammadArslanKhan96 commented
![match_dark](https://github.com/holdex/holdex-venture-studio/assets/98827339/ef2ba6c1-e594-4555-b81f-2d548cec62ec)
![match_light](https://github.com/holdex/holdex-venture-studio/assets/98827339/0a46bfb2-5e37-4be7-a1d8-0e7f9c3e44a2)

@predrag-us  Please check the difference that I've matched with extension, would you please point out what else is missing

2023-07-27 12:31 UTC, predrag-us commented
@MuhammadArslanKhan96 

From these screenshots, one thing is obvious, although many are hidden and you should uncover them by checking the components in Figma. I'll help you ⏤ on this screen, the component states aren't right. 

Back to the obvious thing, a reminder:

> Also, don't forget that you shouldn't alter the design on your own behalf. If you have a suggestion, please address it here in GitHub and we'll act as necessary.

2023-07-27 12:37 UTC, MuhammadArslanKhan96 commented
@predrag-us  I've followed design 100% would you please share any example where I've changed the design
and
what component state is missing

Thanks

2023-07-27 12:47 UTC, predrag-us commented
@MuhammadArslanKhan96 

You haven't followed the design 100% ⏤ there is one image instead of four. 

Some of the mistakes:
- Input text should be white/black (depending on theme) while typing
- Disabled button shouldn't have the blue border while hovering
- Light theme: There are shadows on the input and button, which shouldn't be the case
- Light theme: The button isn't implemented according to the design
- Light theme: The people image border has the wrong color
- Light theme: The card itself has the wrong background color
- ...

There are mistakes on the modal as well, and in the state when you're subscribed. Keep in mind I won't help you like this anymore. You should be able to notice these differences.

2023-07-27 12:59 UTC, MuhammadArslanKhan96 commented
@predrag-us oh its my bad, I didn't check the components state are on a separate place in figma, let me fix. can we make a proto over figma design ? that would be more helpful to debug the frontend component states

2023-07-27 13:02 UTC, predrag-us commented
@MuhammadArslanKhan96 

You don't need a prototype for this kind of issue, you should be able to use Figma Dev Mode.

2023-12-21 18:57 UTC, closed without merging

2023-12-21 18:58 UTC, markholdex commented
There are no updates in the PR within the last 4 hours. The PR has been stale for more than 8 hours. Closing according to our Guideline Rules.