feat: Parse TOC
holdex/holdex-venture-studio pull request #479
Opened 2023-07-31 09:49 UTC by accompany1205

resolves #108 

- [x] Refactor server parse module and add toc parsing logic

2023-08-01 15:51 UTC, georgeciubotaru commented on src/routes/api/google-conversion/+server.ts
> +function parseTOC(toc: Schema$TableOfContents, lists: Schema$List, document: Schema$Document) {
New input payload JSON : https://api.npoint.io/f762379ee2c579535dfb

Problem: Not possible to render table of contents with nested links

<img width="650" alt="image" src="https://github.com/holdex/holdex-venture-studio/assets/8217518/559076d7-4123-41c7-933c-dc3b7b4dbfa1">

Hint: `indent`

Also see the existing (header element parsing to see the `data` fields)

Allowed nesting:
1 level -> h2
2 level -> h3
3 level -> h4
... level -> h4

2023-08-01 16:59 UTC, accompany1205 commented on src/routes/api/google-conversion/+server.ts
> +function parseTOC(toc: Schema$TableOfContents, lists: Schema$List, document: Schema$Document) {
Okay, will check it.

2023-08-03 10:20 UTC, markholdex commented on src/routes/api/google-conversion/+server.ts
> +function parseTOC(toc: Schema$TableOfContents, lists: Schema$List, document: Schema$Document) {
@accompany1205 will you complete this one so we don't leave this PR hanging?

2023-08-03 12:23 UTC, accompany1205 commented on src/routes/api/google-conversion/+server.ts
> +function parseTOC(toc: Schema$TableOfContents, lists: Schema$List, document: Schema$Document) {
Yeah, sure. I jumped into this issue 30 min ago.

2023-08-04 18:53 UTC, accompany1205 commented on src/routes/api/google-conversion/+server.ts
> +function parseTOC(toc: Schema$TableOfContents, lists: Schema$List, document: Schema$Document) {
Please check if this is correct implementation.

2023-08-07 06:56 UTC, georgeciubotaru commented on src/routes/api/google-conversion/+server.ts
> +function parseTOC(toc: Schema$TableOfContents, lists: Schema$List, document: Schema$Document) {
@accompany1205 Okay, I will check

2023-08-07 07:26 UTC, georgeciubotaru commented on src/routes/api/google-conversion/+server.ts
> +            text: sanitizeContent(
@accompany1205 I appreciate that you tried to optimize the code.
But please check the old code for missing things, and try to keep the scope limit.

It's hard now to see what code has been changed, and what not.

2023-08-07 07:27 UTC, georgeciubotaru commented on src/routes/api/google-conversion/+server.ts
> +            indent: {
@accompany1205 We don't need these properties here.

Please check one more time my previous comment.

If I explain somehow unclear let me know

2023-08-15 08:08 UTC, surajsharma commented
@accompany1205 @georgeciubotaru what's the status here? should i ignore this?

2023-08-15 09:24 UTC, georgeciubotaru commented
@surajsharma Let's wait for @accompany1205 to see if he still works on that. if not take it.

2023-08-15 12:31 UTC, accompany1205 commented
> @surajsharma Let's wait for @accompany1205 to see if he still works on that. if not take it.

@georgeciubotaru Sorry, I didn't notice your comments last week.

2023-08-18 00:39 UTC, accompany1205 commented on src/routes/api/google-conversion/+server.ts
> +            text: sanitizeContent(
It was for removing duplicated codes across the codebase because we had too much duplication.

2023-08-18 00:40 UTC, accompany1205 commented on src/routes/api/google-conversion/+server.ts
> +            indent: {
Then how do we indicate nested styling? Only properly I can use for the goal is just indentation properties. like indent first line and indent start.

@georgeciubotaru What do you recommend and what exactly is your method for this?

2023-08-18 05:07 UTC, surajsharma commented on src/routes/api/google-conversion/+server.ts
> +            indent: {
@accompany1205 i believe the indentation would be taken care of in the client, you can safely remove this as George suggested

2023-08-22 09:10 UTC, georgeciubotaru commented
@accompany1205 Please compare the result with the current production API

1. holdex.io API
2. your branch/local API

You've changed and refactored a lot of things, please check carefully.

This task takes too much (more than 4hrs), let's round it to a workable version, and merge.
Then split the problem into smaller issues

2023-08-24 15:58 UTC, georgeciubotaru commented
@accompany1205 You have the JSON object in the description link

2023-08-25 07:57 UTC, georgeciubotaru commented
@accompany1205 Please log the status here, already more than 4 hrs.

Please round this PR to a stable version ASAP and let's merge, the remaining things can be done in the next PRs

2023-08-25 12:23 UTC, accompany1205 commented
@georgeciubotaru Ths logic of functions in `/api/google-conversion` is very complex.
I need more time to complete this.
However, I'm sure that I could show stable version next Monday.

2023-08-25 12:28 UTC, georgeciubotaru commented
@accompany1205 provide a breakdown of your changes?

- Problem 1 (x hours)
- Problem 2 (y hours)

2023-08-29 12:53 UTC, accompany1205 commented
@georgeciubotaru I'm almost done this.
I''m pretty sure that you will see completed result.

2023-08-29 13:10 UTC, georgeciubotaru requested changes
see my comments

2023-08-29 13:45 UTC, accompany1205 commented
1, and 2 are intended changes cuz I thought you are needing those.

2023-08-29 14:01 UTC, georgeciubotaru commented
@accompany1205 We cannot change the block structure, it will affect all the other existing threads, also the parser

2023-08-29 15:02 UTC, georgeciubotaru commented
1.2 remove the `tag` field, not needed

3. not resolved yet

2023-08-29 15:02 UTC, georgeciubotaru requested changes
see my last comment

2023-08-29 15:46 UTC, accompany1205 commented
> see my last comment

![image](https://github.com/holdex/holdex-venture-studio/assets/96562726/88e8e8ba-4c25-4c3a-8966-a09a447c8087)
What is this? I am confusing now. What is the indent you are mentioning?

2023-08-30 06:08 UTC, georgeciubotaru commented
@accompany1205 
![image](https://github.com/holdex/holdex-venture-studio/assets/8217518/205da837-fed2-4c95-bd49-61ad83d26a8e)


You don't need to copy the indent value, you need based on the indent value to positioning elements

1 level => h2
2 level => h3
3 level => h4
4+ level => h4

2023-08-30 10:19 UTC, accompany1205 commented
> @accompany1205 ![image](https://user-images.githubusercontent.com/8217518/264243975-205da837-fed2-4c95-bd49-61ad83d26a8e.png)
> 
> You don't need to copy the indent value, you need based on the indent value to positioning elements
> 
> 1 level => h2 2 level => h3 3 level => h4 4+ level => h4

Where can I see those level stuff in TOC?

Type of elements in toc is all paragraph and I don't see *any* level information for TOC elements.

I am not really sure what you mean with that levels. Perhaps it is for other headers?

2023-08-30 10:24 UTC, accompany1205 commented
> @accompany1205 provide a breakdown of your changes?
> 
> * Problem 1 (x hours)
> * Problem 2 (y hours)

I think I informed this in PR description?

2023-08-30 10:27 UTC, georgeciubotaru commented
@accompany1205 look at the `Hint`

2023-08-30 10:34 UTC, accompany1205 commented
> @accompany1205 look at the `Hint`

2023-09-01 05:43 UTC, georgeciubotaru commented
Not ready Yet

1. Inline links are somehow removed
![image](https://github.com/holdex/holdex-venture-studio/assets/8217518/9b0d833d-1101-4a47-b741-10b78a58aabf)

2. Quote elements don't have `alignment` and `caption` props.


We are working too much on this task, so my solution

1. Stash these changes, or leave the branch as is now
2. Create a new PR with a new branch from the main and do only the `toc` part, without refactoring
3. Refactor one by one, small parts.

2023-09-01 05:44 UTC, georgeciubotaru commented
Log: This PR is rejected and new commits are prohibited.

@accompany1205 FYI

2023-09-04 09:45 UTC, closed without merging