feat: rich link component
holdex/holdex-venture-studio pull request #498
Opened 2023-08-22 12:34 UTC by surajsharma

#371 
eta 4 hours

2023-09-01 07:02 UTC, markholdex commented
@surajsharma any updates here?

2023-09-01 07:02 UTC, markholdex commented
ETA was 4 hours. Did you encounter a blocker?

2023-09-01 07:37 UTC, surajsharma commented
> ETA was 4 hours. Did you encounter a blocker?

no blockers, just occupied with #493 and #496 , will wrap this up presently with the others. eta remains the same

2023-09-04 03:30 UTC, surajsharma commented
@markholdex @georgeciubotaru pls give access to vercel, i cannot inspect the failing build

2023-09-04 05:22 UTC, georgeciubotaru commented
@surajsharma 

You can run `npm run build` and then `npm run preview` and test yourself on your local machine
![image](https://github.com/holdex/holdex-venture-studio/assets/8217518/97b1a796-5631-4255-8b7c-e9f6f6805d4b)

2023-09-04 05:27 UTC, surajsharma commented
> @surajsharma
> 
> You can run `npm run build` and then `npm run preview` and test yourself on your local machine ![image](https://user-images.githubusercontent.com/8217518/265338312-97b1a796-5631-4255-8b7c-e9f6f6805d4b.png)

both `build` and `preview` are running fine on my end @georgeciubotaru

2023-09-04 06:27 UTC, surajsharma commented
@predrag-us @georgeciubotaru also, i think there should be some contingency here for cases where the og calls fails/returns incomplete data...the design has 3 things

<img width="620" alt="image" src="https://github.com/holdex/holdex-venture-studio/assets/5298624/4b6b3a04-1f56-4e4a-90d7-02657b5878b8">


from top to bottom we have:

1) Title 
2) Description
3) truncated link

the truncated link isn't from OG data, but i assume the other two are.

please mention if there needs to be some special text if the og api call fails

2023-09-11 06:22 UTC, georgeciubotaru commented
@surajsharma 

1. Update the repo to use `node:18`
2. Resolve conflicts
3. Ping me to update the node version in Vercel

2023-09-11 07:24 UTC, surajsharma commented
@georgeciubotaru commit resolved, node is `18.16` on local, pls update on vercel

2023-09-11 08:02 UTC, georgeciubotaru commented on src/lib/components/BodyRenderer/item.pug
> +          //- | {console.log(item)}
why don't you remove the logs?

2023-09-11 08:03 UTC, georgeciubotaru commented on src/routes/api/link/+server.ts
> +          {
set a caching value for 5 mins

2023-09-11 08:04 UTC, surajsharma commented on src/lib/components/BodyRenderer/item.pug
> +          //- | {console.log(item)}
@georgeciubotaru sorry, removing now 😰

2023-09-11 08:04 UTC, georgeciubotaru commented on src/lib/components/BodyRenderer/Blocks/richLink.svelte
> +          <slot>
you can obtain truncation via CSS

2023-09-11 08:41 UTC, surajsharma commented on src/routes/api/link/+server.ts
> +          {
done

2023-09-11 08:41 UTC, surajsharma commented on src/lib/components/BodyRenderer/Blocks/richLink.svelte
> +          <slot>
@georgeciubotaru done

2023-09-11 08:42 UTC, georgeciubotaru commented on src/lib/components/BodyRenderer/Blocks/richLink.svelte
> +          <slot>
Also, why do you need `slot`?

2023-09-11 08:44 UTC, surajsharma commented on src/lib/components/BodyRenderer/Blocks/richLink.svelte
> +          <slot>
@georgeciubotaru slot removed

2023-09-11 08:44 UTC, georgeciubotaru commented
@surajsharma See the Vercel Preview comments

2023-09-11 08:46 UTC, surajsharma commented
@georgeciubotaru don't have access 
<img width="447" alt="image" src="https://github.com/holdex/holdex-venture-studio/assets/5298624/d9c23997-2894-409f-80aa-58838fa73f5a">

2023-09-11 08:48 UTC, georgeciubotaru commented
@surajsharma 

- [ ] - 
<img width="520" alt="image" src="https://github.com/holdex/holdex-venture-studio/assets/8217518/996ad527-7d72-4249-a3c1-2566065b010e">

- [ ] - 
<img width="510" alt="image" src="https://github.com/holdex/holdex-venture-studio/assets/8217518/716b5d4a-9810-49ff-8d0f-507ff0405a73">
- [ ] - 
<img width="571" alt="image" src="https://github.com/holdex/holdex-venture-studio/assets/8217518/c74194f9-73ae-495f-9a0b-adf7a020d4c3">
- [ ] - 
<img width="984" alt="image" src="https://github.com/holdex/holdex-venture-studio/assets/8217518/f51cd738-c97f-4ab2-96c3-9b7f8f37f4b7">

2023-09-11 19:05 UTC, surajsharma commented
@georgeciubotaru fixed all issues in last push, pls see

2023-09-12 08:23 UTC, georgeciubotaru commented on src/lib/components/BodyRenderer/Blocks/richLink.svelte
> +            {/if}
you cannot have `a` element inside an `a` element

2023-09-12 08:23 UTC, georgeciubotaru requested changes
see my change

2023-09-12 09:35 UTC, surajsharma commented
> @surajsharma Your solution is not acceptable, please move to another PR.

@georgeciubotaru why is it not acceptable?

2023-09-12 09:51 UTC, georgeciubotaru commented
@surajsharma
1. Opened 3 weeks ago (more than 4hrs)
2.  My involvement time exceeded the actual total development time (4hrs)
3. The code is not production-ready yet

@markholdex, @zolotokrylin  FYI

2023-09-13 10:09 UTC, zolotokrylin commented
@surajsharma 

1. why does your PR take so long? 
2. how much more time do you need to complete PR? George can't baby sit here, he has other things to do.

2023-09-13 10:12 UTC, surajsharma commented
@zolotokrylin 

> 1. why does your PR take so long?

this was in draft for a long while i was working on other PRs

> 2. how much more time do you need to complete PR? George can't baby sit here, he has other things to do.

i understand he is busy, the last interaction here was fixing some of his comments on vercel, from my side it is good to go

2023-09-13 13:47 UTC, georgeciubotaru commented
@surajsharma So what is the ETA to finish this task?

I will review this PR after
- It will be pixel-perfect
- correct semantic

2023-09-14 04:02 UTC, surajsharma commented
@georgeciubotaru 

- here's an image of pixel-perfection

<img width="934" alt="image" src="https://github.com/holdex/holdex-venture-studio/assets/5298624/3ccf7894-2717-431e-93f6-5005452ec063">


- semantics are already fixed

2023-09-14 04:20 UTC, zolotokrylin commented
@georgeciubotaru please check the last time. If the work is done, then it is done. 


And let's just follow the principle we have discussed where we do once a week review on Friday and where we give 2 reviews max.

2023-09-14 06:24 UTC, georgeciubotaru commented on src/lib/components/BodyRenderer/Blocks/richLink.svelte
> +            href={item.data?.url}
you already have the `link` parent block that is clickable, you double the event handler.

the structure should be simple:

old structure example:
<img width="1038" alt="image" src="https://github.com/holdex/holdex-venture-studio/assets/8217518/06456ead-6b9b-4fcd-a678-b0f7d4995dcf">

2023-09-14 06:25 UTC, georgeciubotaru commented on src/routes/(pages)/layout.scss
> +.rich-link-image {
move that style in the related component

2023-09-14 06:29 UTC, georgeciubotaru commented
Your implementation:
![image](https://github.com/holdex/holdex-venture-studio/assets/8217518/3f8a9683-3b4a-49b0-a2e5-c7be37e65a72)

Design:
![image](https://github.com/holdex/holdex-venture-studio/assets/8217518/ade00a39-b00a-4c1e-af55-dcc6e4a62ac8)

2023-09-14 06:35 UTC, surajsharma commented
> Your implementation: ![image](https://user-images.githubusercontent.com/8217518/267876992-3f8a9683-3b4a-49b0-a2e5-c7be37e65a72.png)
> 
> Design: ![image](https://user-images.githubusercontent.com/8217518/267877104-ade00a39-b00a-4c1e-af55-dcc6e4a62ac8.png)

this is pixel perfect overlay of figma export

![image](https://github.com/holdex/holdex-venture-studio/assets/5298624/b4ae55ed-455c-4f8d-be49-f960f6cc71b5)


@georgeciubotaru @zolotokrylin

2023-09-14 06:35 UTC, surajsharma commented on src/routes/(pages)/layout.scss
> +.rich-link-image {
done @georgeciubotaru

2023-09-14 06:35 UTC, surajsharma commented on src/lib/components/BodyRenderer/Blocks/richLink.svelte
> +            href={item.data?.url}
removed extra a tag @georgeciubotaru

2023-09-14 06:38 UTC, surajsharma commented
@georgeciubotaru 

<img width="671" alt="image" src="https://github.com/holdex/holdex-venture-studio/assets/5298624/63561045-90ce-440b-9bad-863e1f837d74">



design:
<img width="129" alt="image" src="https://github.com/holdex/holdex-venture-studio/assets/5298624/d07ff17c-f85e-47d2-8d4f-3e57898a3617">

2023-09-18 13:10 UTC, georgeciubotaru commented
@surajsharma 

1. The paddings are wrong (check for image padding)
2. The structure is not semantic
 - I've placed a screenshot with the old structure, check it and try to have the same one

2023-09-18 14:32 UTC, surajsharma commented
@georgeciubotaru 

> 2. The structure is not semantic

pls give a list of semantic elements you would like to see used here, there are many `divs` and `spans` so not exactly sure what you are asking for here, i will repace with semantic elements where i see fit

> 1. The paddings are wrong (check for image padding)

i have added screenshot with pixel perfect showing no gap in padding, here's another video showing dimensions are exactly as in design as of now



https://github.com/holdex/holdex-venture-studio/assets/5298624/b65e8b95-7c40-414b-8051-6f493ffcb883

2023-09-19 09:54 UTC, surajsharma commented
@georgeciubotaru i believe this is good to go as per your directions, i have added semantic elements, fixed padding

2023-09-21 07:59 UTC, georgeciubotaru commented
@surajsharma Please check the screenshot with the semantics from the old implementation.

In your case, you have an `a` element inside a `span` wrapper that has `clickHandler`,
-  case of click to the link you are doubling the event
- then entire block should be a link

2023-09-21 08:01 UTC, georgeciubotaru commented
@surajsharma Regarding image padding

You have a `figure` block that should have padding and the `rich-link-image` to fit the space inside it

2023-09-22 05:26 UTC, surajsharma commented
> @surajsharma Regarding image padding
> 
> You have a `figure` block that should have padding and the `rich-link-image` to fit the space inside it

i had to use some creative css here to ensure aspect ratio, for this reason, took out the `figure` and replaced it with a section, renamed css classes to remove confusion as to whats happenning

```
  style={`background-size:cover; background-position: center;
    background-repeat: no-repeat; background-image: url(${ogdata?.image[0]?.url});`}

``

2023-09-22 06:17 UTC, surajsharma commented
> @surajsharma Please check the screenshot with the semantics from the old implementation.
> 
> In your case, you have an `a` element inside a `span` wrapper that has `clickHandler`,
> -  case of click to the link you are doubling the event
> - then entire block should be a link

@georgeciubotaru let me check

2023-09-22 06:57 UTC, surajsharma commented
@georgeciubotaru all issues should be fixed now, apologies for the trouble with semantics

2023-09-26 06:59 UTC, georgeciubotaru commented
@surajsharma 

1. Please strictly follow the semantics from my screenshot (old implementation)
2. Title/href truncation should be done strictly in CSS (no JS functions)

2023-09-26 07:03 UTC, surajsharma commented
> @surajsharma
> 
> 1. Please strictly follow the semantics from my screenshot (old implementation)
> 2. Title/href truncation should be done strictly in CSS (no JS functions)

@georgeciubotaru please leave comments in code only, otherwise i don't understand so well

2023-10-09 00:40 UTC, surajsharma commented on src/lib/components/BodyRenderer/Blocks/richLink.svelte
> +    let textWithoutPrefix = url.replace(/^https?:\/\//, '');
@georgeciubotaru 

> 2. Title/href truncation should be done strictly in CSS (no JS functions)

is it possible to truncate with regex match in css? because elsewhere in the code we seem to be making use of regex for href truncation

2023-10-11 10:13 UTC, georgeciubotaru requested changes
see my comment

2023-10-11 13:48 UTC, georgeciubotaru commented on src/lib/components/BodyRenderer/Blocks/richLink.svelte
> +<span
@surajsharma If you check the old structure, you see that the 

`span` wrapper doesn't have any click handler, and the first child is an `a` tag with a link

2023-12-29 07:47 UTC, closed without merging