feat: link styling  `/about` team members
holdex/holdex-venture-studio pull request #504
Opened 2023-08-29 17:29 UTC by CTAPCKPIM

2023-08-29 17:32 UTC, CTAPCKPIM commented
@georgeciubotaru 

Tell me how I can achieve the goal, I tried different things and so far I have not been able to complete the task

![image](https://github.com/holdex/holdex-venture-studio/assets/83241890/acf9009f-29d9-4a30-a365-c3c67a323d71)

When I remove the second check mark, the style becomes as it should, but I have not yet found where these lines are, I will be grateful for the hint

2023-08-30 06:16 UTC, georgeciubotaru commented
@CTAPCKPIM 

You are on the good path

1. If you will check the `BodyRenderer/item.svelte` file you will find global styles applied to `b|em|strong` that also override the `a` elements text.

I think you get what you need to do next.

2023-08-30 20:12 UTC, CTAPCKPIM commented
@georgeciubotaru 
- Done, check pls

2023-08-31 07:03 UTC, georgeciubotaru commented
@CTAPCKPIM Not the correct version.

Try to identify what you need to do:

- We have `b` elements that have white text color, there can be around the project (different elements)
- You need to change that text-color for inline elements inside a link.

2023-08-31 10:38 UTC, georgeciubotaru commented on src/lib/components/BodyRenderer/inline.svelte
> +  :global(a),
you have `Link` component where you can please this code.

remove comments above

2023-08-31 16:29 UTC, georgeciubotaru commented on src/lib/components/BodyRenderer/Blocks/link.svelte
> +    @apply text-accent1-default
```suggestion
  a :global(*)
    @apply text-inherit
```

2023-08-31 16:29 UTC, georgeciubotaru commented on src/lib/components/BodyParser/blocks.ts
> +        text: `<b>${match[1]}</b>`, // redact here (this file)? (test)
```suggestion
        text: `<b>${match[1]}</b>`,
```

2023-08-31 16:29 UTC, georgeciubotaru commented on src/lib/components/BodyParser/blocks.ts
> +        text: `<b>${match[1]}</b>`, // redact here (this file)? (test)
```suggestion
        text: `<b>${match[1]}</b>`,
```

2023-09-01 05:26 UTC, georgeciubotaru requested changes
see my change

2023-09-01 13:21 UTC, georgeciubotaru approved these changes

2023-09-01 13:22 UTC, merged