fix: edge case of table with two cols
holdex/holdex-venture-studio pull request #517
Opened 2023-09-08 06:37 UTC by surajsharma

#516 
eta 5 misn

2023-09-08 06:49 UTC, surajsharma commented
log: although i am not expecting more edge cases here, will like to see how a three col table acts with the current fix, my guess is it should be scrollable for a few pixels (single digit), with the shades in place

2023-09-08 07:17 UTC, georgeciubotaru commented
@surajsharma You can mutate the table and test all use-cases
From 1 col table to 10 col table.

Let us know the results

2023-09-08 07:19 UTC, surajsharma commented
> @surajsharma You can mutate the table and test all use-cases From 1 col table to 10 col table.
> 
> Let us know the results

sure, can you pls share the link for the google doc? @georgeciubotaru

2023-09-08 07:20 UTC, georgeciubotaru commented
@surajsharma Do that in the code, you have `cells` object. try to mutate it

2023-09-08 07:55 UTC, surajsharma commented
> @surajsharma Do that in the code, you have `cells` object. try to mutate it

@georgeciubotaru i tested by mutating the cells and found everything is as expected. 1, 2, 3, 4 cols and beyond i see no artifacts or formatting issues, please tell me if you find anything

2023-09-11 06:20 UTC, georgeciubotaru requested changes
do the cleanup and optimizations

2023-09-11 07:54 UTC, surajsharma commented
@georgeciubotaru should be fixed now, most of the code is the same as recently merged feat #496

2023-09-11 08:58 UTC, georgeciubotaru commented on src/lib/components/BodyRenderer/Blocks/table.svelte
> +  import Node from './Tweet/components/html/node.svelte';
why do you need this import?

2023-09-11 08:59 UTC, georgeciubotaru commented on src/lib/components/BodyRenderer/Blocks/table.pug
>  +table-scroll-shades
you can add `+if` above mixin and don't show mixin at all

2023-09-11 09:34 UTC, surajsharma commented on src/lib/components/BodyRenderer/Blocks/table.svelte
> +  import Node from './Tweet/components/html/node.svelte';
@georgeciubotaru removed

2023-09-11 09:35 UTC, surajsharma commented on src/lib/components/BodyRenderer/Blocks/table.pug
>  +table-scroll-shades
@georgeciubotaru done

2023-09-11 10:01 UTC, georgeciubotaru commented on src/lib/components/BodyRenderer/Blocks/table.pug
> ++if("cells[0].length > 2")
Your solution doesn't work
https://holdex-venture-studio-git-516-bugfix-table-holdex-accelerator.vercel.app/c/announcements/article-components

Think about other solution

2023-09-11 11:47 UTC, surajsharma commented on src/lib/components/BodyRenderer/Blocks/table.pug
> ++if("cells[0].length > 2")
@georgeciubotaru can you pinpoint the issue here? table renders fine for me at the link given

2023-09-11 13:04 UTC, surajsharma commented on src/lib/components/BodyRenderer/Blocks/table.pug
> ++if("cells[0].length > 2")
@georgeciubotaru i already tried that before pushing this, turns out there is never any difference between parent and child widths, got any other ideas?

<img width="216" alt="image" src="https://github.com/holdex/holdex-venture-studio/assets/5298624/12185d7a-3391-47e3-b816-946b698d7450">

2023-09-11 14:24 UTC, georgeciubotaru commented on src/lib/components/BodyRenderer/Blocks/table.pug
> ++if("cells[0].length > 2")
<img width="1117" alt="image" src="https://github.com/holdex/holdex-venture-studio/assets/8217518/3a2b7f00-387e-46ff-be3e-8fbdd921f21e">
<img width="1440" alt="image" src="https://github.com/holdex/holdex-venture-studio/assets/8217518/fe0518bc-e1f2-4fb5-9091-ea8b01e0415f">
<img width="1090" alt="image" src="https://github.com/holdex/holdex-venture-studio/assets/8217518/a359e4b1-da89-4c04-8629-277151efd1a6">

2023-09-11 15:26 UTC, surajsharma commented on src/lib/components/BodyRenderer/Blocks/table.pug
> ++if("cells[0].length > 2")
@georgeciubotaru the line 

`maxScroll = tableScrollElement.clientWidth - node!.parentElement!.clientWidth;`

already captures this difference..

2023-09-11 16:32 UTC, surajsharma commented on src/lib/components/BodyRenderer/Blocks/table.pug
> ++if("cells[0].length > 2")
@georgeciubotaru came up with a function that tests if the element has scroll, hides the shade if there is no scrolling happening, works nice pls see

2023-09-11 17:31 UTC, surajsharma commented on src/lib/components/BodyRenderer/Blocks/table.pug
> ++if("cells[0].length > 2")
implemented different solution

2023-09-12 08:42 UTC, surajsharma commented on src/lib/components/BodyRenderer/Blocks/table.svelte
> +    const tableScrollElement = document.getElementById('table-scroll');
@georgeciubotaru what do you mean? already tested with multiple tables on the same page

<img width="484" alt="image" src="https://github.com/holdex/holdex-venture-studio/assets/5298624/d45a7c78-761d-41e8-b673-bbf62f035099">

<img width="834" alt="image" src="https://github.com/holdex/holdex-venture-studio/assets/5298624/e25113b5-3bc8-46ce-b13a-52d5d5318352">

2023-09-12 08:59 UTC, georgeciubotaru commented on src/lib/components/BodyRenderer/Blocks/table.svelte
> +        isRightEnd = true;
please optimize the code

2023-09-12 09:33 UTC, surajsharma commented on src/lib/components/BodyRenderer/Blocks/table.svelte
> +        isRightEnd = true;
done @georgeciubotaru

2023-09-12 12:04 UTC, georgeciubotaru commented on src/lib/components/BodyRenderer/Blocks/table.svelte
> +    const tableScrollElement = document.getElementById('table-scroll');
@surajsharma What do you see wrong here?
<img width="430" alt="image" src="https://github.com/holdex/holdex-venture-studio/assets/8217518/b11a666e-de17-4b08-9189-2b6debae64b5">

2023-09-18 09:13 UTC, georgeciubotaru commented on src/lib/components/BodyRenderer/Blocks/table.svelte
> +    const tableScrollElement = document.getElementById('table-scroll');
@surajsharma No answer here

2023-09-18 09:41 UTC, surajsharma commented on src/lib/components/BodyRenderer/Blocks/table.svelte
> +    const tableScrollElement = document.getElementById('table-scroll');
@georgeciubotaru because i did not find an issue here, i can only guess at your comment

2023-09-18 10:08 UTC, georgeciubotaru commented on src/lib/components/BodyRenderer/Blocks/table.svelte
> +    const tableScrollElement = document.getElementById('table-scroll');
@surajsharma Optimise the condition for `isRightEnd` and `isScroller` they are dependent one to another

isRightEnd = conditions || condition2
isScroller = !isRightEnd && condition3

2023-09-18 10:31 UTC, surajsharma commented on src/lib/components/BodyRenderer/Blocks/table.svelte
> +    const tableScrollElement = document.getElementById('table-scroll');
@georgeciubotaru although i have done as you suggested, i did not optimize this in the first place because here, the function `hasReachedRightEnd` is called declaratively, so for some resolutions/devices (ipad Mini , Air etc) the explicit `if` check helps in toggling the shade off.


although theoretically your optimisation should work since the entire function body is executed on scroll, this extra guard helps making sure that the shade is off when the end of the scroll is reached.

therefore i recommend we let the `if` statement be here.

2023-09-18 12:52 UTC, georgeciubotaru approved these changes

2023-09-18 12:55 UTC, merged