Article hero redesign
holdex/holdex-venture-studio pull request #531
Opened 2023-11-03 11:03 UTC by angelicawill

I Implemented new article hero section 
#526

2023-11-03 13:57 UTC, markholdex commented
Test article: https://holdex-venture-studio-git-fork-angeli-8be7c1-holdex-accelerator.vercel.app/c/announcements/article-components

2023-11-03 16:09 UTC, markholdex commented
Visual tested - all good.

2023-11-03 16:29 UTC, georgeciubotaru requested changes
see my comment

2023-11-03 16:29 UTC, georgeciubotaru commented on src/routes/(pages)/c/[slug]/[messageSlug]/template.pug
>      .author-block(class="flex flex-col bg-l1 border border-solid border-l4 rounded-xl w-full dark:bg-l2")
@angelicawill This block class inform us about an author block but in reality its jist a block for horizontal line.

Can you double check and update the classes accordingly?

2023-11-03 16:53 UTC, georgeciubotaru reviewed
another comment

2023-11-03 16:53 UTC, georgeciubotaru commented on src/routes/(pages)/c/[slug]/[messageSlug]/template.pug
> -        //- TextParagraph(class="flex flex-wrap gap-3 xs:gap-2" textColor="text-t3")
@angelicawill please the commented lines as was initially.

2023-11-03 20:17 UTC, angelicawill commented on src/routes/(pages)/c/[slug]/[messageSlug]/template.pug
> -        //- TextParagraph(class="flex flex-wrap gap-3 xs:gap-2" textColor="text-t3")
just to clarify, reverting the commented lines means i dont display the views count and comments, correct?

2023-11-03 20:30 UTC, angelicawill commented on src/routes/(pages)/c/[slug]/[messageSlug]/template.pug
>      .author-block(class="flex flex-col bg-l1 border border-solid border-l4 rounded-xl w-full dark:bg-l2")
Fixed this in the new commit

2023-11-06 07:40 UTC, georgeciubotaru commented on src/routes/(pages)/c/[slug]/[messageSlug]/template.pug
> -        //- TextParagraph(class="flex flex-wrap gap-3 xs:gap-2" textColor="text-t3")
@angelicawill Correct!

2023-11-06 07:53 UTC, angelicawill commented on src/routes/(pages)/c/[slug]/[messageSlug]/template.pug
> -        //- TextParagraph(class="flex flex-wrap gap-3 xs:gap-2" textColor="text-t3")
@georgeciubotaru fixed as instructed! Please check.

2023-11-06 08:28 UTC, georgeciubotaru approved these changes

2023-11-06 08:55 UTC, zolotokrylin requested changes
- design is not pixel perfect
- duplicated article images (https://holdex-venture-studio-git-fork-angeli-8be7c1-holdex-accelerator.vercel.app/c/announcements/zebec-protocol)

2023-11-06 08:56 UTC, zolotokrylin commented
@georgeciubotaru @markholdex double check when you approve things.

2023-11-06 14:56 UTC, markholdex commented
Duplicated hero images issue has been solved. We now have a dedicated input in Google Doc plugin.

2023-11-06 15:01 UTC, markholdex commented
Thanks @georgeciubotaru

2023-11-08 07:09 UTC, zolotokrylin reviewed
Looks fine for me

P.S. I just did a brief visual review without PP comparison:

1. @markholdex leaving it up to you regarding PP
2. @georgeciubotaru your call regarding code

2023-11-08 08:04 UTC, georgeciubotaru commented on src/routes/(pages)/c/[slug]/[messageSlug]/template.pug
> +        span(class="mr-[5px]") ,
@angelicawill let's keep the old value

2023-11-08 08:04 UTC, georgeciubotaru commented on src/routes/(pages)/c/[slug]/[messageSlug]/template.pug
> +          .edit-wrapper(class="flex gap-[5px] justify-end smDown:justify-start")
same here, let's keep the old `gap` value

2023-11-08 08:06 UTC, angelicawill commented on src/routes/(pages)/c/[slug]/[messageSlug]/template.pug
> +        span(class="mr-[5px]") ,
@georgeciubotaru okay. but keeping the old value will make it not pixel perfect to the figma file, is that okay?

2023-11-08 08:06 UTC, georgeciubotaru reviewed
besides comments, all good in the code review

2023-11-08 15:28 UTC, angelicawill commented
@georgeciubotaru the spacings mentioned are reverted back to the old value

2023-11-08 19:27 UTC, markholdex commented on src/routes/(pages)/c/[slug]/[messageSlug]/template.pug
> +        span(class="mr-[5px]") ,
@angelicawill in this case, the problems need to be addressed more globally instead of making a quick patch for the current section. Otherwise, the patch will remain in place and create other bugs in the future. 

We can discuss this issue in a separate problem statement.

2023-11-08 19:28 UTC, markholdex approved these changes

2023-11-08 19:28 UTC, merged

2023-11-08 19:29 UTC, markholdex commented
@angelicawill please update the hours spent on this PR. Thanks!