fix: add thread CTA component
holdex/holdex-venture-studio pull request #537
Opened 2023-12-01 16:28 UTC by DaoSpirit

#390 
extended api/google-conversion parser to support CTA component.
extended renderer parser to support CTA component.
implemented UI of CTA section.

2023-12-04 12:11 UTC, georgeciubotaru commented on src/lib/components/BodyRenderer/Blocks/cta.svelte
> +    {/if}
please check for existing components

2023-12-04 12:34 UTC, georgeciubotaru commented on src/lib/components/BodyRenderer/Blocks/cta.svelte
> +    {/if}
@DaoSpirit https://github.com/holdex/holdex-venture-studio/tree/main/src/lib/components/Button

2023-12-04 12:36 UTC, DaoSpirit commented on src/lib/components/BodyRenderer/Blocks/cta.svelte
> +    {/if}
Actually I tried with that but some annoying mismatch with secondary button when it comes with light mode

2023-12-05 14:25 UTC, DaoSpirit commented on src/lib/components/BodyRenderer/Blocks/cta.svelte
> +    {/if}
@georgeciubotaru  I've implemented it with existing button.
but secondary button will be different from Figma design.
plz check and leave feedback.

2023-12-08 07:25 UTC, georgeciubotaru requested changes
see my comment

2023-12-08 07:37 UTC, DaoSpirit commented on src/lib/components/BodyRenderer/Blocks/cta.svelte
> +    {/if}
sure

2023-12-11 13:56 UTC, DaoSpirit commented
I fixed feedback
@georgeciubotaru

2023-12-12 09:29 UTC, georgeciubotaru commented on src/lib/components/BodyRenderer/Blocks/cta.svelte
> +        right: 20px
you can combine the common styles

2023-12-12 09:30 UTC, georgeciubotaru commented on src/lib/components/BodyRenderer/Blocks/cta.svelte
> +        border: none
no need for this one, as the buttons are standable components

2023-12-12 09:30 UTC, georgeciubotaru commented on src/lib/components/BodyRenderer/Blocks/cta.svelte
> +      </Button>
```suggestion
      <Button
        class="cta-button text-t1 border-secondary"
        variant="secondary"
        size="large"
        href={item.link2.url}
        label="{item.link2.text}"
      />
```

2023-12-12 09:31 UTC, georgeciubotaru commented on src/lib/components/BodyRenderer/Blocks/cta.svelte
> +      </Button>
```suggestion
      <Button class="cta-button text-t4" variant="primary" size="large" href={item.link1.url} label="{item.link1.text}"/>
```

2023-12-12 09:33 UTC, georgeciubotaru commented on src/lib/components/BodyRenderer/Blocks/cta.svelte
> +  <div class="ml-auto cta-buttons dark:cta-buttons-dark flex flex-row gap-4 xs:flex-col xs:w-full">
cleanup unused classes

2023-12-12 09:34 UTC, georgeciubotaru commented on tailwind.config.cjs
> +      'cta-title': [
why did you update these styles?

2023-12-12 09:34 UTC, georgeciubotaru commented on src/lib/components/BodyRenderer/Blocks/cta.svelte
> +  </div>
wrong font styles

2023-12-12 09:34 UTC, georgeciubotaru requested changes
see my changes

2023-12-14 10:33 UTC, DaoSpirit commented on src/lib/components/BodyRenderer/Blocks/cta.svelte
> +  <div class="ml-auto cta-buttons dark:cta-buttons-dark flex flex-row gap-4 xs:flex-col xs:w-full">
All styles are used, nothing to omit

2023-12-14 10:36 UTC, DaoSpirit commented
updated feedback @georgeciubotaru 
some parts are not clear.
I left comment, plz check and share opinion.

2023-12-18 07:29 UTC, georgeciubotaru commented on src/lib/components/BodyRenderer/Blocks/cta.svelte
> +        border: none
@DaoSpirit The button styles are out of your PR scope. Please implement only the styles related to that component

2023-12-18 07:33 UTC, georgeciubotaru commented on src/lib/components/BodyRenderer/Blocks/cta.svelte
> +  </div>
@DaoSpirit Still the font doesn't match the ones from Figma

2023-12-18 07:33 UTC, georgeciubotaru commented on src/lib/components/BodyRenderer/Blocks/cta.svelte
> +  <div class="ml-auto cta-buttons dark:cta-buttons-dark flex flex-row gap-4 xs:flex-col xs:w-full">
see this one

2023-12-18 08:13 UTC, DaoSpirit commented on src/lib/components/BodyRenderer/Blocks/cta.svelte
> +        border: none
but removing this component will not matched with figma design.
is it okay?

2023-12-18 08:25 UTC, georgeciubotaru commented on src/lib/components/BodyRenderer/Blocks/cta.svelte
> +        border: none
@DaoSpirit Did you update your branch with the changes from main branch?

2023-12-19 07:00 UTC, georgeciubotaru requested changes
see unresolved comments

2023-12-20 09:13 UTC, georgeciubotaru commented
@markholdex, @angelicawill  Can you please take the visual review, all good from my side.

2023-12-20 09:14 UTC, georgeciubotaru submitted a review, later dismissed

2023-12-20 12:53 UTC, zolotokrylin commented
@DaoSpirit how many hours of work did you spend before requesting a review and how many hours in total, including fixing rejected PR?

2023-12-20 13:06 UTC, DaoSpirit commented
before review: 8 hours
after review: 4 hours
total: 12 hours

2023-12-20 17:18 UTC, angelicawill reviewed
@DaoSpirit There's some minor pixel perfect issue, please check my comments. Thanks!

2023-12-20 17:18 UTC, angelicawill commented on src/lib/components/BodyRenderer/Blocks/cta.svelte
> +  class="relative cta flex flex-row xs:flex-col gap-6 w-full border border-solid border-l4 rounded-xl p-4 bg-l1 dark:bg-l2"
should add xs:gap-4 to match the design in desktop view

2023-12-20 17:18 UTC, angelicawill commented on src/lib/components/BodyRenderer/Blocks/cta.svelte
> +  <div class="ml-auto flex flex-row gap-4 xs:flex-col xs:w-full py-1.75">
```suggestion
  <div class="ml-auto flex flex-row gap-2 xs:gap-4 xs:flex-col xs:w-full">
```

2023-12-20 17:38 UTC, zolotokrylin requested changes
@DaoSpirit see Angelica's comments above.

@angelicawill in the future use REJECT feature in that case. Thanks

2023-12-20 18:01 UTC, DaoSpirit commented on src/lib/components/BodyRenderer/Blocks/cta.svelte
> +  <div class="ml-auto flex flex-row gap-4 xs:flex-col xs:w-full py-1.75">
suggested change doesn't match with design, I think

2023-12-20 18:16 UTC, angelicawill commented on src/lib/components/BodyRenderer/Blocks/cta.svelte
> +  <div class="ml-auto flex flex-row gap-4 xs:flex-col xs:w-full py-1.75">
@DaoSpirit may I know which part?

2023-12-20 18:30 UTC, DaoSpirit commented on src/lib/components/BodyRenderer/Blocks/cta.svelte
> +  <div class="ml-auto flex flex-row gap-4 xs:flex-col xs:w-full py-1.75">
padding top&bottom doesn't work @angelicawill

2023-12-20 18:38 UTC, DaoSpirit commented on src/lib/components/BodyRenderer/Blocks/cta.svelte
> +  class="relative cta flex flex-row xs:flex-col gap-6 w-full border border-solid border-l4 rounded-xl p-4 bg-l1 dark:bg-l2"
it seems gap-6 for desktop view @angelicawill

2023-12-21 06:16 UTC, angelicawill commented on src/lib/components/BodyRenderer/Blocks/cta.svelte
> +  <div class="ml-auto flex flex-row gap-4 xs:flex-col xs:w-full py-1.75">
@DaoSpirit there's no padding on the button wrapper in the design
![CleanShot 2023-12-21 at 14 14 31@2x](https://github.com/holdex/holdex-venture-studio/assets/78342026/a881b21f-4bc4-431d-b9cf-9237ee0667a5)

2023-12-21 06:45 UTC, angelicawill commented on src/lib/components/BodyRenderer/Blocks/cta.svelte
> +  class="relative cta flex flex-row xs:flex-col gap-6 w-full border border-solid border-l4 rounded-xl p-4 bg-l1 dark:bg-l2"
![CleanShot 2023-12-21 at 14 15 23@2x](https://github.com/holdex/holdex-venture-studio/assets/78342026/9713426f-4c89-49e5-aa66-16cf4ddb84a7)

@DaoSpirit the gap is 16px, which is gap-4 I believe

2023-12-21 19:06 UTC, markholdex commented
@DaoSpirit can you please update us on the status of this PR? Do you plan to complete it? 

If so, I would appreciate it if you would respect our Guidelines and don't leave a PR handing without updates. Also, the PR completion time should not exceed 4 hours. I propose you wrap things up soon, otherwise, the PR will be closed without merge. Thanks! 🙏

2023-12-21 20:02 UTC, DaoSpirit commented on src/lib/components/BodyRenderer/Blocks/cta.svelte
> +  <div class="ml-auto flex flex-row gap-4 xs:flex-col xs:w-full py-1.75">
![image](https://github.com/holdex/holdex-venture-studio/assets/146466572/cbfa1793-bf6c-4326-a6e8-d14c63baa9a6)
fixed result is screenshot.

2023-12-21 20:10 UTC, DaoSpirit commented on src/lib/components/BodyRenderer/Blocks/cta.svelte
> +  <div class="ml-auto flex flex-row gap-4 xs:flex-col xs:w-full py-1.75">
as we can see in your screenshot,
gap-4 xs:gap-2 is matched with design
not gap-2 xs:gap-4
@angelicawill

2023-12-22 03:50 UTC, zolotokrylin commented
@markholdex there are updates. See comments above your message.

2023-12-22 04:04 UTC, angelicawill commented on src/lib/components/BodyRenderer/Blocks/cta.svelte
> +  <div class="ml-auto flex flex-row gap-4 xs:flex-col xs:w-full py-1.75">
@DaoSpirit you're right, I got mixed up. gap-4 xs:gap-2 is the right one. sorry for that.

In this case my suggested change will be 
  <div class="ml-auto flex flex-row gap-4 xs:gap-2 xs:flex-col xs:w-full">

2023-12-22 04:08 UTC, angelicawill commented on src/lib/components/BodyRenderer/Blocks/cta.svelte
> +  class="relative cta flex flex-row xs:flex-col gap-6 w-full border border-solid border-l4 rounded-xl p-4 bg-l1 dark:bg-l2"
and here my suggested change will be adding `xs:gap-6 gap-4` to accommodate the desktop and mobile view design

2023-12-22 04:38 UTC, zolotokrylin commented
@georgeciubotaru @DaoSpirit @angelicawill please "resolve" the resolved comments. Those which are not resolved, resolve ASAP and let's move on to the next step of the interview.

2023-12-22 06:56 UTC, DaoSpirit commented on src/lib/components/BodyRenderer/Blocks/cta.svelte
> +  <div class="ml-auto flex flex-row gap-4 xs:flex-col xs:w-full py-1.75">
@angelicawill  we should add py-2 to match the design.
I'll share screenshot. and button size is too big
![image](https://github.com/holdex/holdex-venture-studio/assets/146466572/5d8a6f40-83dc-4abd-acb3-bc3e900477b3)

2023-12-22 07:17 UTC, angelicawill commented on src/lib/components/BodyRenderer/Blocks/cta.svelte
> +  <div class="ml-auto flex flex-row gap-4 xs:flex-col xs:w-full py-1.75">
@DaoSpirit I see. I just checked, and seems that it's an issue from the button component, which stretches in height to fit the space. I'll fix the button component to include `height:fit-content`, and you can remove the py-2. I'll create a separate PR for this

2023-12-22 07:24 UTC, DaoSpirit commented on src/lib/components/BodyRenderer/Blocks/cta.svelte
> +  <div class="ml-auto flex flex-row gap-4 xs:flex-col xs:w-full py-1.75">
okay
so should I push updated one without fixing button height? @angelicawill

2023-12-22 07:35 UTC, angelicawill commented on src/lib/components/BodyRenderer/Blocks/cta.svelte
> +  <div class="ml-auto flex flex-row gap-4 xs:flex-col xs:w-full py-1.75">
@DaoSpirit yes, but please add vertical center aligning so the button component will be positioned in the middle when the height changes. thank you!

2023-12-22 07:45 UTC, angelicawill commented on src/lib/components/BodyRenderer/Blocks/cta.svelte
> +  <div class="ml-auto flex flex-row gap-4 xs:flex-col xs:w-full py-1.75">
@DaoSpirit fyi I opened a PR that fixes the button issue, #555. It hasn't been merged yet, but you can test out the button style to see if the CTA match with the design now. 🙏

2023-12-22 07:52 UTC, DaoSpirit commented on src/lib/components/BodyRenderer/Blocks/cta.svelte
> +  <div class="ml-auto flex flex-row gap-4 xs:flex-col xs:w-full py-1.75">
I checked it @angelicawill 
it matched with the design.
but adding my-auto to align vertical center shows the same result with changed button style.
I'll push commit and plz check

2023-12-22 08:01 UTC, angelicawill approved these changes
All good from my side.

2023-12-22 08:16 UTC, markholdex commented on src/lib/components/BodyRenderer/Blocks/cta.svelte
> +        right: 20px
@DaoSpirit have you implemented these changes?

2023-12-22 08:17 UTC, markholdex commented on src/lib/components/BodyRenderer/Blocks/cta.svelte
> +        border: none
@DaoSpirit is this comment resolved?

2023-12-22 08:25 UTC, georgeciubotaru commented on src/lib/components/BodyRenderer/index.svelte
> +  ];
```suggestion
```

2023-12-22 08:25 UTC, georgeciubotaru commented on src/lib/components/BodyRenderer/index.svelte
>  {/each}
```suggestion
{#each blocks as item, index}
  <Item {item} {index} />
{/each}
```

2023-12-22 08:26 UTC, georgeciubotaru approved these changes

2023-12-22 08:40 UTC, merged