fix: remove unwanted space between link enclosed with brackets
holdex/holdex-venture-studio pull request #551
Opened 2023-12-13 07:20 UTC by angelicawill

resolves #538 

Time spent: 3 hours

2023-12-13 07:42 UTC, angelicawill commented
The message received by the BodyParser from the google-conversion API has space around the link for links surrounded by brackets, and I still don't understand why.  
![CleanShot 2023-12-13 at 15 41 53](https://github.com/holdex/holdex-venture-studio/assets/78342026/1d302bd0-4900-475a-967d-fd5ea4bdb5c3)


So what I do is handling this in the render process, basically just trimming trailing whitespace for texts that ends or starts with brackets. This can be extended for other symbols as well.

This solution solves the problem in the "about" page, but I think this is a band-aid solution and doesn't address the problem at its core, but it's the best I can do now since other tasks are more urgent. 

@zolotokrylin

2023-12-13 09:13 UTC, zolotokrylin requested changes

2023-12-13 09:13 UTC, zolotokrylin commented on src/lib/components/BodyRenderer/inline.svelte
> +  }
@angelicawill  if I want the case to be like `(\space` it won't work? 
I think it won't work.
Thus, you need to fix this on the level of the `link` render function.

@georgeciubotaru correct me if I am wrong

2023-12-13 11:43 UTC, angelicawill commented on src/lib/components/BodyRenderer/inline.svelte
> +  }
@zolotokrylin Sorry, I don't get what you mean. Can you please elaborate more? Thank you

2023-12-14 08:59 UTC, zolotokrylin commented on src/lib/components/BodyRenderer/inline.svelte
> +  }
@angelicawill 
if I have a text in google document like this: 
<img width="415" alt="image" src="https://github.com/holdex/holdex-venture-studio/assets/1125014/c818fec2-4575-4be8-b253-804a1676f435">

Will it render on our website like this: 
a - `( text )`, or like this:
b - `(text)`
? 

 Should be `a`

2023-12-14 09:27 UTC, angelicawill commented on src/lib/components/BodyRenderer/inline.svelte
> +  }
@zolotokrylin I understand now. That's a case that I failed to recognize

2023-12-14 17:56 UTC, merged