fix(ui): corrects the display of the date on price chart
holdex/holdex-venture-studio pull request #561
Opened 2023-12-28 18:47 UTC by CTAPCKPIM

ETA: 1-4 hrs

2023-12-28 19:55 UTC, CTAPCKPIM commented
- https://momentjs.com/

2023-12-28 20:09 UTC, CTAPCKPIM commented
> * https://momentjs.com/

Problem: 
- Don't update display of the date

2023-12-28 20:53 UTC, CTAPCKPIM commented
@georgeciubotaru 
- I searched the place for an update of the component, let's merge, and in the next `PR` I finish

2023-12-29 06:34 UTC, zolotokrylin requested changes
1. wrong PR title 
2. why you even working on this issue? is it is not important!

2023-12-29 06:35 UTC, zolotokrylin commented
There is no problem with the date. It is a fake and problem, and a solution is a waste of resources.
You need to work on something that brings value. If in doubt, ask leads in Discord about the problems to work on.

2023-12-29 11:13 UTC, CTAPCKPIM commented
- goal: redo the task

2024-01-03 09:01 UTC, georgeciubotaru commented on src/lib/components/Tooltip/Tooltip.stories.svelte
> +<script>
no need for this file

2024-01-03 09:02 UTC, georgeciubotaru commented on src/lib/components/Chart/template.pug
> +    ) i
no in this scope

2024-01-03 09:02 UTC, georgeciubotaru commented on .vscode/settings.json
> +    "source.fixAll.eslint": "explicit"
revert yhis

2024-01-03 09:04 UTC, georgeciubotaru commented on src/lib/components/Tooltip/style.sass
> +            transform: rotate(90deg)
please check so the styles will match the Figma Design

2024-01-03 09:04 UTC, georgeciubotaru requested changes
see my comments.

2024-01-10 11:19 UTC, CTAPCKPIM commented
@georgeciubotaru 
- Can you check and if need to correct my pls

2024-01-10 16:44 UTC, georgeciubotaru commented on src/lib/components/Tooltip/style.sass
> +            transform: rotate(90deg)
@CTAPCKPIM The Figma UI https://www.figma.com/file/39MGGVIGQ1bL3FgVzuXEdC/Holdex?type=design&node-id=455-3579&mode=design&t=uMzOCWVu90AXDKxo-4

2024-01-11 16:02 UTC, CTAPCKPIM commented
@georgeciubotaru 
- Done, check pls

2024-02-17 09:16 UTC, zolotokrylin commented
@georgeciubotaru

2024-05-18 10:34 UTC, zolotokrylin commented
@georgeciubotaru

2025-02-14 09:34 UTC, closed without merging