feat: add customers' testimonial component to portfolio articles
holdex/holdex-venture-studio pull request #570
Opened 2024-01-12 18:24 UTC by blueogin

2024-01-15 16:33 UTC, markholdex commented
Hey @blueogin any updates on the PR? I'm following based on the guidelines we agreed on. 

p.s. I understand you're also busy with your own things too.

2024-01-15 19:42 UTC, blueogin commented
Hey @markholdex 
the issue (https://github.com/holdex/holdex-venture-studio/issues/494) is fixed and you can check on this PR

2024-01-16 15:27 UTC, markholdex requested changes
@blueogin I launched Vercel deployment on your branch (you can also have a look) and the testimonial block is not being displayed. 

https://holdex-venture-studio-git-fork-blueog-536616-holdex-accelerator.vercel.app/c/announcements/article-components

<img width="1225" alt="image" src="https://github.com/holdex/holdex-venture-studio/assets/46079535/dfdac506-1984-4a75-9353-b944fe102d9a">

2024-01-16 15:54 UTC, blueogin commented
I will have a look again and ping you once it's done

2024-01-16 20:08 UTC, markholdex requested changes
@blueogin good job 👍 it works good now both on desktop and mobile. 

2 things I wanted to confirm:

1. Did you check the size of the profile picture? Feels like it's squashed.
1. Any way for us to include this decoration?
<img width="921" alt="Screenshot 2024-01-16 at 22 06 05" src="https://github.com/holdex/holdex-venture-studio/assets/46079535/911c1a98-5ba4-4665-ade3-b8850717e520">

2024-01-17 14:43 UTC, blueogin commented
I worked on this issue 8+ hrs

2024-01-17 14:45 UTC, blueogin commented
@markholdex 
I followed figma design(width & height = 48px)
is it ok if I fix like this (width = 48px & height = 60px)?
The height is automatically adjusted for the image size
![image](https://github.com/holdex/holdex-venture-studio/assets/43612769/947f591c-6474-4ba7-a622-106dd7899986)

2024-01-17 15:23 UTC, blueogin commented
Fixed and pushed changes
Current status looks like below
![image](https://github.com/holdex/holdex-venture-studio/assets/43612769/2bce9bd5-9f4e-4aa0-bee0-7bb025fb7d4b)

2024-01-17 15:29 UTC, angelicawill commented
@blueogin Can you adjust the image scaling so it proportionally envelops the entire container? The aim is to ensure the image seamlessly covers the entire space without any distortion or squashing.

2024-01-17 15:30 UTC, angelicawill requested changes
see my comment above

2024-01-17 16:58 UTC, blueogin commented
@angelicawill
Sorry for the late response
fixed the image scaling and below is current status
![image](https://github.com/holdex/holdex-venture-studio/assets/43612769/d4047ac4-ab29-4ee9-92bb-c2807612bb70)

2024-01-17 18:09 UTC, markholdex commented
> @angelicawill Sorry for the late response fixed the image scaling and below is current status ![image](https://private-user-images.githubusercontent.com/43612769/297456353-d4047ac4-ab29-4ee9-92bb-c2807612bb70.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1MTUyMTgsIm5iZiI6MTcwNTUxNDkxOCwicGF0aCI6Ii80MzYxMjc2OS8yOTc0NTYzNTMtZDQwNDdhYzQtYWIyOS00ZWU5LTkyYmItYzI4MDc2MTJiYjcwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE3VDE4MDgzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdkNWE3MDI2OGY0YWNiODFhZjQ0MDEyMDk1YmMxOWFlNWZkOTZkMTcwN2UzNmQ1MDM5Njg4NjBkMzFiYzMyYzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xXcDyo9Xj5RP6mAE9_1pUIwp4aj9jXNiwPmfk9uBq5I)

This is what I meant when I initially rejected your PR. Sorry I couldn't reply earlier but good that you understood each other and you @blueogin fixed it.  Will check in preview now.

2024-01-17 18:16 UTC, markholdex requested changes
@blueogin the table component was affected and broken by your changes. You can compare with the article on stage. 

<img width="783" alt="image" src="https://github.com/holdex/holdex-venture-studio/assets/46079535/8ff71e73-478c-4d3f-aa01-44276a115e51">

---

https://stage.holdex.io/c/announcements/article-components

---

<img width="815" alt="image" src="https://github.com/holdex/holdex-venture-studio/assets/46079535/fda95658-e040-4fa2-9fc8-a95bcdae7a42">

2024-01-17 18:27 UTC, blueogin commented
@markholdex 
I worked on this issue 9+ hrs so far
And fixed and the table component is not affected atm
![image](https://github.com/holdex/holdex-venture-studio/assets/43612769/4a921583-7d3f-4bfe-bd99-828cd8023668)
![image](https://github.com/holdex/holdex-venture-studio/assets/43612769/05ebd2af-51a8-4433-8a1f-7412a4d99d61)
![image](https://github.com/holdex/holdex-venture-studio/assets/43612769/b4bc142b-2e7b-4906-b6af-8fcd017a8bd7)

2024-01-18 02:51 UTC, angelicawill requested changes
@blueogin Can you make such that the blue light strobe effect and the border in the same line? Right now it seems that they are not positioned in the same line.
<img width="738" alt="CleanShot 2024-01-18 at 10 47 14@2x" src="https://github.com/holdex/holdex-venture-studio/assets/78342026/86530391-e291-4104-b9f5-045d55b1bdf7">

Also, the "blue" color for light mode and dark mode is different, which you can see in figma, so make sure you adjust the color of the light strobe effect accordingly.

2024-01-18 18:29 UTC, markholdex submitted a review, later dismissed

2024-01-18 18:48 UTC, georgeciubotaru commented on src/lib/components/BodyParser/blocks.ts
> +export type TestimonialElement = {
```suggestion
};

export type TestimonialElement = {
```

2024-01-18 18:49 UTC, georgeciubotaru commented on src/lib/components/BodyRenderer/Blocks/testimonial.svelte
> +      right: 5%
please optimize here the css

2024-01-18 18:50 UTC, georgeciubotaru commented on src/lib/components/BodyRenderer/Blocks/testimonial.svelte
> +        <div class="avatar rounded-full" style="background-image: url('{item.picture?.url}')" />
why you didn't use here `img` tag?

2024-01-18 18:51 UTC, georgeciubotaru commented on src/lib/components/BodyRenderer/index.svelte
> +  });
This one is good, but please move it in the `api/google-conversion` same as `cta` handling

2024-01-18 18:51 UTC, georgeciubotaru commented on src/lib/components/BodyRenderer/utils.ts
move this in the API folder

2024-01-18 18:52 UTC, georgeciubotaru commented on src/lib/components/BodyRenderer/Blocks/testimonial.svelte
> +  $: themeContext = getContext('theme');
```suggestion
  let themeContext = getContext('theme');
```

the context is already reactive

2024-01-18 18:53 UTC, georgeciubotaru requested changes
see my comments.

Overal good job 👍

2024-01-18 18:53 UTC, blueogin commented on src/lib/components/BodyRenderer/index.svelte
> +  });
Already changed `api/google-conversion` and it seems that the data does not from this api

2024-01-18 18:53 UTC, blueogin commented on src/lib/components/BodyRenderer/utils.ts
Already changed `api/google-conversion` and it seems that the data does not from this api

2024-01-18 19:00 UTC, blueogin commented on src/lib/components/BodyRenderer/Blocks/testimonial.svelte
> +        <div class="avatar rounded-full" style="background-image: url('{item.picture?.url}')" />
Because of image squash
if we use div/background we can avoid it
Please check here
https://github.com/holdex/holdex-venture-studio/pull/570#issuecomment-1896037121
This is the result when I use `img` tag

2024-01-18 19:06 UTC, georgeciubotaru commented on src/lib/components/BodyRenderer/Blocks/testimonial.svelte
> +        <div class="avatar rounded-full" style="background-image: url('{item.picture?.url}')" />
Try this behavior

`<img class="w-12 h-12 rounded-full  object-cover object-center"/>` and let me know

2024-01-18 19:13 UTC, blueogin commented on src/lib/components/BodyRenderer/Blocks/testimonial.svelte
> +      right: 5%
Okay

2024-01-18 19:13 UTC, blueogin commented on src/lib/components/BodyRenderer/Blocks/testimonial.svelte
> +      right: 5%
Yup

2024-01-18 19:14 UTC, blueogin commented on src/lib/components/BodyRenderer/Blocks/testimonial.svelte
> +        <div class="avatar rounded-full" style="background-image: url('{item.picture?.url}')" />
Current status
![image](https://github.com/holdex/holdex-venture-studio/assets/43612769/ad54d479-29d8-4f32-95e0-b321e3e73af4)
![image](https://github.com/holdex/holdex-venture-studio/assets/43612769/ae245b45-a7bf-46f3-ad11-5b2ea785fb8c)

2024-01-18 19:28 UTC, blueogin commented
@georgeciubotaru 
Answered and pushed changes for your comments
Thanks for your point!

2024-01-18 19:30 UTC, georgeciubotaru commented on src/lib/components/BodyRenderer/utils.ts
The idea is that we need to resync the Google Document so it will be converted using this API, then you should receive the payload in the UI

2024-01-18 19:32 UTC, georgeciubotaru commented on src/lib/components/BodyRenderer/Blocks/testimonial.svelte
> +        <div class="avatar rounded-full" style="background-image: url('{item.picture?.url}')" />
@blueogin The original image size is square or not?

2024-01-18 19:36 UTC, blueogin commented on src/lib/components/BodyRenderer/Blocks/testimonial.svelte
> +        <div class="avatar rounded-full" style="background-image: url('{item.picture?.url}')" />
The original image is not square
In my personal pespective, I think by using <div>'s background style is better

2024-01-18 19:39 UTC, blueogin commented on src/lib/components/BodyRenderer/utils.ts
You mean after fetching data from graphql server, then post to `google-conversion` to get parsed payload?
Overall, process parsing activity by call the google-conversion api

2024-01-18 19:41 UTC, georgeciubotaru commented on src/lib/components/BodyRenderer/Blocks/testimonial.svelte
> +        <div class="avatar rounded-full" style="background-image: url('{item.picture?.url}')" />
@markholdex, @zolotokrylin From a semantic perspective we should use `img`. But if we want to use `img` we need to have squared images.

2024-01-19 00:00 UTC, zolotokrylin commented on src/lib/components/BodyRenderer/Blocks/testimonial.svelte
> +        <div class="avatar rounded-full" style="background-image: url('{item.picture?.url}')" />
100% the image tag must be used.

2024-01-19 04:41 UTC, blueogin commented on src/lib/components/BodyRenderer/Blocks/testimonial.svelte
> +        <div class="avatar rounded-full" style="background-image: url('{item.picture?.url}')" />
No problem 
I will push current codebase (Looks like above image)

2024-01-19 06:27 UTC, zolotokrylin commented on src/lib/components/BodyRenderer/Blocks/testimonial.svelte
> +        <div class="avatar rounded-full" style="background-image: url('{item.picture?.url}')" />
@blueogin thanks, but we need to solve the problem completely. If we use `img` tag, we need to make sure the design matches.

2024-01-19 06:42 UTC, georgeciubotaru commented on src/lib/components/BodyRenderer/utils.ts
@blueogin How the process work

Google Document -> Convert Google Doc to our syntax (api/google-conversion) -> Publish and store the payload in our backend -> Query the payload using Graphql -> render blocks

2024-01-19 14:52 UTC, blueogin commented on src/lib/components/BodyRenderer/utils.ts
Sure @georgeciubotaru 
I noticed this workflow.
According this, I should add parsing function in `api/google-conversion` and get parsed data on FE, Classify the data for testimonial, inject this to the testimonial UI component then shows it in the right place.
As you can see in my codebase, I already added the parsing function on `google-conversion` part.
@markholdex  Could you check this please?

2024-01-19 15:01 UTC, blueogin commented on src/lib/components/BodyRenderer/Blocks/testimonial.svelte
> +        <div class="avatar rounded-full" style="background-image: url('{item.picture?.url}')" />
@zolotokrylin 
As george said, if we use `img` tag, we should have squared image to fit the design

2024-01-19 15:31 UTC, markholdex commented on src/lib/components/BodyRenderer/Blocks/testimonial.svelte
> +        <div class="avatar rounded-full" style="background-image: url('{item.picture?.url}')" />
@blueogin do you mean the IMG URL should be of an image that is square? If so, no problem. We will have it.

2024-01-19 15:32 UTC, markholdex commented
@blueogin can you please mark as resolved the comments you already processed?

2024-01-19 16:20 UTC, markholdex commented on src/lib/components/BodyRenderer/index.svelte
> +  });
@blueogin did you move this logic of parsing into `google-conversion`? Or you are saying that the functionality doesn't work when you move it?

2024-01-19 16:21 UTC, blueogin commented
@markholdex 
Processed discussions are marked as resolved

2024-01-19 16:55 UTC, blueogin commented on src/lib/components/BodyRenderer/index.svelte
> +  });
@markholdex 
Once I move this functionality to the `google-conversion` it does not work.

2024-01-19 16:56 UTC, blueogin commented on src/lib/components/BodyRenderer/index.svelte
> +  });
I can not test it on my side, because I do not know the request data form

2024-01-19 17:11 UTC, markholdex commented
@blueogin alright here is the situation now. Let me update you on the context as I probably provided you with wrong info. It will help us move further. 

You added the parsing logic in the front-end (in the renderer) which is good. It helps us to confirm your implementation is working in the current preview environment. However, when moving to production and mering, we don't require the logic anymore. Because you have moved the logic already in the `api/google-conversion` and once we merge to `main`, our back-end will call the google-conversion API, and save the `testimonial` table as a component instead of just the table. So the next time page is loaded, it will be rendered automatically as `testimonial` component without the requirement of having the parsing logic in the FE renderer. 

Makes sense? This is why George asked for your changes.

2024-01-19 17:17 UTC, markholdex commented
@blueogin so what you need to do, is comment the logic from BodyRenderer. We will merge it. And if works good on production, you will be required to submit another PR which removes the commented BodyRenderer

2024-01-19 17:19 UTC, blueogin commented
Totally understand @markholdex 
Thanks for the confirmation!
I will eliminate all parsing logic on FE, and will push it atm

2024-01-19 17:30 UTC, markholdex commented
@blueogin remember to comment the logic too. Not only adding comments.

2024-01-19 17:38 UTC, blueogin commented
@markholdex 

> @blueogin remember to comment the logic too. Not only adding comments.

What does this mean?
Current comments are ok?

2024-01-19 17:47 UTC, markholdex commented
@blueogin current comments are OK. but the logic is still in the body renderer

2024-01-19 17:56 UTC, blueogin commented
> @blueogin so what you need to do, is comment the logic from BodyRenderer. We will merge it. And if works good on production, you will be required to submit another PR which removes the commented BodyRenderer
@markholdex 
I am little confused with this comment
I understood that leave the logic in bodyrenderer and add comment to it
Then productions works well, I will submit another pr to eliminate the parsing logic in body renderer

2024-01-19 18:07 UTC, markholdex commented
> @markholdex I am little confused with this comment I understood that leave the logic in bodyrenderer as it is and only add comment to it to describe current situation Then productions works well, I will submit another pr to eliminate the parsing logic in body renderer
> 
> > @blueogin so what you need to do, is comment the logic from BodyRenderer. We will merge it. And if works good on production, you will be required to submit another PR which removes the commented BodyRenderer

Yes please, eliminate the bodyrenderer logic for now. I suggested instead of eliminating - to comment it (hide it). But it's cool to remove it too.

2024-01-19 18:12 UTC, blueogin commented
@markholdex 
Eliminated parsing logic from `BodyRenderer`
I will mark the conversion with george as resolved

2024-01-19 18:49 UTC, markholdex approved these changes

2024-01-19 18:50 UTC, merged

2024-01-22 04:38 UTC, zolotokrylin commented
@markholdex @blueogin what's the relevant github issue? I can't see any issues being attached.