feat: updated jobs category tags and OG tags #571
holdex/holdex-venture-studio pull request #574
Opened 2024-01-24 14:16 UTC by neverm25

2024-01-24 20:06 UTC, markholdex commented
@neverm25 please leave a lof of the time you spent on the solution. Thanks!

2024-01-25 08:14 UTC, angelicawill approved these changes
Test: 
https://holdex-venture-studio-896ff6oxi-holdex-accelerator.vercel.app/c/jobs/senior-designer

Checked in telegram, twitter, and whatsapp. OG title and image works 

<img width="640" alt="CleanShot 2024-01-25 at 16 12 10@2x" src="https://github.com/holdex/holdex-venture-studio/assets/78342026/d5faf182-e596-4548-b0e4-184ed2932320">

2024-01-25 10:58 UTC, neverm25 commented
@markholdex I updated the comment.

2024-01-25 13:06 UTC, zolotokrylin requested changes

2024-01-25 13:06 UTC, zolotokrylin commented on src/routes/(pages)/c/[slug]/[messageSlug]/+page.svelte
> +  title="{message.title} - Job | Holdex"
does it mean that the "Job" string will be on all pages, including this page? https://holdex.io/c/learn/how-to-stake-tokens-with-uniswap-v3-staking-program. This would be a wrong thing.

2024-01-25 13:08 UTC, zolotokrylin commented
There was never a problem with telegram.
Check this 
<img width="562" alt="image" src="https://github.com/holdex/holdex-venture-studio/assets/1125014/e892cae3-7248-417f-b2f0-e760aceb74d4">

2024-01-25 15:22 UTC, neverm25 commented on src/routes/(pages)/c/[slug]/[messageSlug]/+page.svelte
> +  title="{message.title} - Job | Holdex"
Oh, let me check again.

2024-01-25 15:41 UTC, neverm25 commented on src/routes/(pages)/c/[slug]/[messageSlug]/+page.svelte
> +  title="{message.title} - Job | Holdex"
@zolotokrylin, I resolved the problem.
Please check again.

2024-01-25 16:55 UTC, zolotokrylin commented on src/routes/(pages)/c/[slug]/[messageSlug]/+page.svelte
> +  title="{message.title} - Job | Holdex"
@neverm25 please request review

2024-01-25 16:56 UTC, zolotokrylin commented on .vscode/settings.json
> +    "source.fixAll.eslint": "explicit"
why this has changed?

2024-01-25 17:08 UTC, neverm25 commented on .vscode/settings.json
> +    "source.fixAll.eslint": "explicit"
sorry.
It's because of my VS code.
I will revert it.

2024-01-25 17:11 UTC, neverm25 commented on .vscode/settings.json
> +    "source.fixAll.eslint": "explicit"
@zolotokrylin, I reverted.

2024-01-26 03:02 UTC, zolotokrylin commented on src/routes/(pages)/c/[slug]/[messageSlug]/+page.svelte
> +  imagePath={message.cover ? message.cover : '/default-cover.png'}
why did this attribute change?

2024-01-26 10:09 UTC, neverm25 commented on src/routes/(pages)/c/[slug]/[messageSlug]/+page.svelte
> +  imagePath={message.cover ? message.cover : '/default-cover.png'}
As you can see, `message.cover` is undefined so the value is returned as '/default-cover.png'.
![image](https://github.com/holdex/holdex-venture-studio/assets/138539187/55e71490-d35d-4ade-88c9-1a9891b72488)

![image](https://github.com/holdex/holdex-venture-studio/assets/138539187/dd069fbf-a412-4d55-8366-5995581263e0)

Then, in `MetaTags` components we had to set the imagePath to show the image. 
'/default-cover.png' doesn't work for the `imageUrl`. It works for the `imagePath`.
![image](https://github.com/holdex/holdex-venture-studio/assets/138539187/b12a9537-ee02-479d-86fa-4b05bccbd397)

2024-01-26 17:20 UTC, markholdex requested changes
@neverm25 there is a problem with the current implementation. A `false` text is  applied to the title of Non Jobs articles: 

https://holdex-venture-studio-git-fork-neverm-119c16-holdex-accelerator.vercel.app/c/announcements/for-startups

<img width="595" alt="Screenshot 2024-01-26 at 19 24 15" src="https://github.com/holdex/holdex-venture-studio/assets/46079535/101abd94-4fe7-4ef3-9f92-463d8025ce27">

2024-01-26 17:25 UTC, neverm25 commented
@markholdex please check again.

This is preview url.
https://holdex-venture-studio-dh4cr4btu-holdex-accelerator.vercel.app/c/announcements/portfolio-pickle-finance
This is my deploy url.
https://holdex-venture-studio-dev.vercel.app/c/announcements/portfolio-pickle-finance

2024-01-26 17:27 UTC, markholdex commented
@neverm25 I updated my comment. Check the problem you introduced.

2024-01-26 17:28 UTC, neverm25 commented
Let me check again.

2024-01-26 17:32 UTC, neverm25 commented
I updated. Please check again.

https://holdex-venture-studio-dev.vercel.app/c/announcements/portfolio-pickle-finance

2024-01-26 17:55 UTC, markholdex commented
@neverm25 now it works.

2024-01-26 17:58 UTC, markholdex approved these changes

2024-01-26 18:01 UTC, merged